interface ZIF_TRANSPORT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB398A3171',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB398AB171',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB39897171',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB398B3171',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB3989B171',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB398A7171',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '0800279570E01ED9B08B20DB398AF171',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB39895171',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB39891171',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB398A1171',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB398B9171',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB398B7171',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279570E01ED9B08B20DB398BB171',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0800279570E01ED9B08ADE8340A8914C' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'Z_TRANSPORT' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '0800279570E01ED9B08B20DB3988B171',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '0800279570E01ED9B08B20DB39893171',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '0800279570E01ED9B08B20DB3988F171',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '0800279570E01ED9B08B20DB3989F171',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  MY_COMPONENT                   TYPE STRING VALUE 'MY_COMPONENT',
  TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
  SOME_COMP                      TYPE STRING VALUE 'SOME_COMP',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0800279570E01ED9B08B20DB3988D171',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '0800279570E01ED9B08B20DB398BD171',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '0800279570E01ED9B08B20DB398BF171',
      END OF ROOT,
    END OF SC_QUERY .
  constants:
    BEGIN OF SC_QUERY_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF SELECT_BY_ELEMENTS,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 MY_COMPONENT                   TYPE STRING VALUE 'MY_COMPONENT',
 TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
 SOME_COMP                      TYPE STRING VALUE 'SOME_COMP',
        END OF SELECT_BY_ELEMENTS,
      END OF ROOT,
    END OF SC_QUERY_ATTRIBUTE .
endinterface.
