INTERFACE z_1c_upd_types
  PUBLIC .

  TYPES:
    BEGIN OF t_info,
      id    TYPE string,
      value TYPE string,
    END OF t_info.
  TYPES tt_info TYPE STANDARD TABLE OF t_info WITH EMPTY KEY.

  TYPES:
    BEGIN OF t_material,
      line_number          TYPE string,
      name                 TYPE string,
      okei_material        TYPE string,
      quantity             TYPE string,
      price                TYPE string,
      amount_no_vat        TYPE string,
      vat                  TYPE string,
      amount_with_vat      TYPE string,
      id                   TYPE string,
      additional_parameter TYPE string,
      ozon_id              TYPE string,
      wildberries_id       TYPE string,

    END OF t_material.
  TYPES tt_materials TYPE STANDARD TABLE OF t_material WITH EMPTY KEY.

  TYPES:
    BEGIN OF  t_upd_file,
      program_version TYPE string,
      from_version    TYPE string,
      file_id         TYPE string,
      BEGIN OF info_doc_turnover,
        id_sender   TYPE string,
        id_receiver TYPE string,
        BEGIN OF info_edo_provider,
          id_edo            TYPE string,
          organisation_inn  TYPE string,
          organisation_name TYPE string,
        END OF info_edo_provider,
      END OF info_doc_turnover,
      BEGIN OF document,
        organisation_name    TYPE string,
        time_inf             TYPE string,
        date_inf             TYPE string,
        document_name        TYPE string,
        document_description TYPE string,
        function             TYPE string,
        knd                  TYPE string,
        BEGIN OF invoice_info,
          okv_code       TYPE string,
          invoice_date   TYPE string,
          invoice_number TYPE string,
          BEGIN OF seller,
            BEGIN OF seller_id,
              BEGIN OF ip_info,
                inn TYPE string,
                BEGIN OF contact,
                  first_name  TYPE string,
                  last_name   TYPE string,
                  medium_name TYPE string,
                END OF contact,
              END OF ip_info,
            END OF seller_id,
            BEGIN OF address,
              street      TYPE string,
              streen      TYPE string,
              building    TYPE string,
              region_code TYPE string,
              apartment   TYPE string,
              house       TYPE string,
              city        TYPE string,
            END OF address,
            phone TYPE string,
            BEGIN OF bank_account ,
              account_number TYPE string,
              BEGIN OF bank,
                corresponding_account_number TYPE string,
                bik                          TYPE string,
                bank_name                    TYPE string,
              END OF bank,
            END OF bank_account,
          END OF seller,
          BEGIN OF receiver,
            BEGIN OF id,
              inn               TYPE string,
              organisation_name TYPE string,
              kpp               TYPE string,
            END OF id,
            BEGIN OF address,
              region_code TYPE string,
              area        TYPE string,
              settlement  TYPE string,
              index       TYPE string,
            END OF address,
          END OF receiver,
          BEGIN OF buyer,
            BEGIN OF id,
              inn               TYPE string,
              organisation_name TYPE string,
              kpp               TYPE string,
            END OF id,
            BEGIN OF address,
              text_address TYPE string,
              code         TYPE string,
            END OF address,
          END OF buyer,
          info           TYPE tt_info,
        END OF invoice_info,
        materials            TYPE tt_materials,
      END OF document,

    END OF t_upd_file.



ENDINTERFACE.
