CLASS zcl_1coz_categories_service DEFINITION
INHERITING FROM zcl_1coz_abstract_service
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_1coz_categories_service IMPLEMENTATION.
ENDCLASS.
